# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

parse_git_branch() {
     git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/(\1)/'
}

export KUBECONFIG=$HOME/.kube/config
alias k=kubectl 
source <(kubectl completion bash)
complete -F __start_kubectl k 
alias ksetns="kubectl config set-context --current --namespace"
alias ksetuser="kubectl config set-context --current --user"
export PS1="\u@\h \[\e[32m\]\w \[\e[91m\]\$(parse_git_branch)\[\e[00m\]$ "
alias cdi="cd ~/vnext/platform-shared-tools/packages/installer"
alias cdml="cd ~/vnext/platform-shared-tools/packages/installer/mini-loop"
alias cdaws="cd ~/vnext/platform-shared-tools/packages/installer/gke"
alias cdvn="cd ~/vnext/platform-shared-tools"
# alias cdku="cd ~/td-kube-utils"
# alias cdnl="cd ~/td-kube-utils/vm/ndogo-loop"
export PATH=$PATH:$HOME/gcp-scripts:$HOME/common-scripts
